---
- name: Java OpenJDK PlayBook
  hosts: all
  become: yes

  vars_files:
    - vars/vars.yml

  tasks:

  - debug:
      msg: "Install Java OpenJDK"
    
  - include_role:
      name: ansible-role-java
    vars:
        - java_packages: '{{ openjdk_packages }}'
